import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
	id "com.gradleup.shadow" version "9.4.1"
    //id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.21'
}


def nonJar = configurations.create('nonJar')
tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

sourceSets.main.resources {
    srcDir('src/generated/resources')
    exclude("**/*.bbmodel")
    exclude("src/generated/**/.cache")
}

repositories {
    flatDir {
        dirs 'libs'
    }
    mavenLocal()
}

base {
    archivesName = mod_id
}
java.toolchain.languageVersion = JavaLanguageVersion.of(25)

configurations {
    libraries
    implementation.extendsFrom libraries
}
runs { 
    configureEach {
        dependencies {
            runtime project.configurations.libraries
        }
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }
    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    clientData {
        arguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}
configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    implementation(libraries("org.graalvm.polyglot:polyglot:${graaljs_version}"))
    implementation(libraries("org.graalvm.js:js-language:${graaljs_version}"))
    implementation(libraries("org.graalvm.truffle:truffle-runtime:${graaljs_version}"))
}
tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            graaljs_version        : graaljs_version
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = mod_id
            from components.java
        }
    }
    repositories {
        mavenLocal()
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/An-Mao/JavaRepo")
            credentials {
                username = "An-Mao"
                password = "ghp_" + System.getenv("GTT")
            }
        }
        maven {
            name = "LocalRepo"
            allowInsecureProtocol = true
            url = uri(System.getenv("LOCAL_MAVEN") + "/repository/maven-releases")
            credentials {
                username = "am"
                password = System.getenv("N_P")
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}



tasks.shadowJar {
    from(nonJar)
    archiveBaseName.set(mod_id)
    archiveClassifier.set("all")
    mergeServiceFiles()
    from sourceSets.main.output
    configurations = [
            project.configurations.libraries
    ]
    dependencies {
        exclude(dependency("org.graalvm.js:js-community:.*"))
        exclude(dependency("org.graalvm.js:js:.*"))
    }
}

tasks.register('shadowJarLite', ShadowJar) {
    from(nonJar)
    archiveBaseName.set(mod_id)
    archiveClassifier.set("lite")
    mergeServiceFiles()
    from sourceSets.main.output
    configurations = [
            project.configurations.libraries
    ]

    dependencies {
        exclude(dependency("org.graalvm.js:js-community:.*"))
        exclude(dependency("org.graalvm.js:js:.*"))
        exclude(dependency("org.graalvm.sdk:collections:.*"))
        exclude(dependency("org.graalvm.sdk:word:.*"))
        exclude(dependency("org.graalvm.sdk:nativeimage:.*"))
        exclude(dependency("org.graalvm.truffle:truffle-compiler:.*"))
    }

}

/*
tasks{
    shadowJar {
        archiveBaseName.set(mod_id)
        archiveClassifier.set("all")

//        manifest {
//            attributes("Main-Class" : "dev.anye.mc.graaljs.GraalJS")
//        }

        mergeServiceFiles()
        from sourceSets.main.output
        configurations = [
                project.configurations.libraries
        ]

//        configurations.libraries.each { dep ->
//            from zipTree(dep)  // 包含 libraries 配置中的依赖
//        }
    }
}

 */
/*
tasks.register('shadowJarLite', ShadowJar) {
    archiveBaseName.set(mod_id)
    archiveClassifier.set("lite")
    //manifest {
    //    attributes("Main-Class" : "dev.anye.mc.graaljs.GraalJS")
    //}
    mergeServiceFiles()
    from sourceSets.main.output
    configurations = [
            project.configurations.lite
    ]

    //exclude 'org/graalvm/collections/**'
    //exclude 'org/graalvm/nativeimage/**'
    //exclude 'org/graalvm/word/**'
    //exclude 'com/oracle/svm/core/annotate/**'
    //exclude 'module-info.class'

    //doLast {
    //    exclude 'org/graalvm/collections/**'
    //}

    //configurations.lite.each { dep ->
    //    from zipTree(dep)
    //}

}

 */
tasks.named("build") {
    dependsOn shadowJar
    dependsOn shadowJarLite
}
